version: "3.9"

services:
  taskcloud:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    image: taskcloud-backend:latest
    container_name: taskcloud-backend
    env_file:
      - .env
    networks:
      - taskcloud_net
    ports:
      - "8080:8080"   # Behind existing reverse proxy (recommended on a shared VPS)
    volumes:
      - caddy_data:/data       # Caddy cert storage
      - caddy_config:/config   # Caddy config storage
    restart: unless-stopped
    # Uncomment if using the bundled Postgres service below
    # depends_on:
    #   - postgres

  # Optional Postgres service (enable if you want in-container DB)
  # Be mindful of other containers on your VPS; ensure port and network don't conflict.
  postgres:
    image: postgres:16
    container_name: taskcloud-postgres
    environment:
      - POSTGRES_DB=taskcloud
      - POSTGRES_USER=taskcloud
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-change-me-in-production}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - taskcloud_net
    restart: unless-stopped
    # Expose only if you need to connect from host; otherwise omit
    # ports:
    #   - "5432:5432"

networks:
  taskcloud_net:
    name: taskcloud_net

volumes:
  caddy_data:
  caddy_config:
  pgdata:
